zabbix_export:
  version: '7.0'
  template_groups:
  - uuid: 3427078345254ffdab6884173069c572
    name: Retigra/Tasks/System
  templates:
  - uuid: e86ad28d3a6e4dbe8cf8aedd1f642b20
    template: Generic System properties by SNMP
    name: Generic System properties by SNMP
    description: Gathers system properties via SNMPv3.
    groups:
    - name: Retigra/Tasks/System
    items:
    - uuid: 5486bebb9f1149dcba8a26541c7b0c49
      name: 'System: uptime threshold'
      type: CALCULATED
      key: system.uptimeThreshold
      delay: '300'
      history: 7d
      params: '{$T_SYSTEM_UPTIME_THRESH}'
      description: Stores the threshold used in uptime alerts
      tags:
      - tag: Application
        value: System::Metadata
    - uuid: c853490ed4a34d31ad900dfdd0aeff92
      name: 'System: uptime'
      type: SNMP_AGENT
      snmp_oid: SNMPv2-MIB::sysUpTime.0
      key: SystemUptime
      delay: '300'
      history: 7d
      units: uptime
      description: |
        The time since the network management portion of the system was last re-initialized.

        32 bit counter
      preprocessing:
      - type: MULTIPLIER
        parameters:
        - '0.01'
      tags:
      - tag: Application
        value: System::Metrics
      triggers:
      - uuid: 690d12ae6504429ea50105d12ee1a99a
        expression: last(/Generic System properties by SNMP/SystemUptime)={$T_SYSTEM_UPTIME_THRESH}
        name: 'System: {HOST.NAME} has restarted'
        priority: WARNING
        description: The system has been rebooted less then {$T_SYSTEM_UPTIME_THRESH}
          seconds ago.
    - uuid: 022f3dd0333946c698aeeb2fea9de3de
      name: 'System: contact details'
      type: SNMP_AGENT
      snmp_oid: SNMPv2-MIB::sysContact.0
      key: system[contact]
      delay: '7200'
      history: 7d
      value_type: CHAR
      trends: '0'
      description: The textual identification of the contact person for this managed
        node, together with information on how to contact this person.  If no contact
        information is known, the value is the zero-length string.
      inventory_link: CONTACT
      tags:
      - tag: Application
        value: System::Metrics
      triggers:
      - uuid: 58df1280718643999930087d20c26170
        expression: abs(change(/Generic System properties by SNMP/system[contact]))=1
        name: 'System: Contact details have been changed for {HOST.NAME}'
        priority: INFO
        description: The configured contact for this host has been changed.
      - uuid: 017cbdca3a9a433db8fa7194ec91261c
        expression: abs(change(/Generic System properties by SNMP/system[contact]))=1
        name: 'System: Serial number of {HOST.NAME} has changed'
        priority: INFO
        description: The device serial number of this host has changed.
    - uuid: 2e9d099d66f4484bb65e2ab0ca6ea172
      name: 'System: device description'
      type: SNMP_AGENT
      snmp_oid: SNMPv2-MIB::sysDescr.0
      key: system[description]
      delay: '7200'
      history: 7d
      value_type: CHAR
      trends: '0'
      description: A textual description of the entity.  This value should include
        the full name and version identification of the system's hardware type, software
        operating-system, and networking software.
      inventory_link: OS_FULL
      tags:
      - tag: Application
        value: System::Metrics
    - uuid: 3690e6b0919f411cad778ee4bb8220bd
      name: 'System: firmware'
      type: SNMP_AGENT
      snmp_oid: '{$I_SYSTEM_FIRMWARE_OID}'
      key: system[firmware]
      delay: '3600'
      history: 14d
      value_type: CHAR
      trends: '0'
      inventory_link: OS_SHORT
      tags:
      - tag: Application
        value: System::Metrics
      triggers:
      - uuid: aa0b5e7811464751975a7d00b44b9078
        expression: find(/Generic System properties by SNMP/system[firmware],,"iregexp","{$V_SOFTWARE_APP_D}")=0
        name: 'System: Firmware is not the required version'
        priority: INFO
      - uuid: 26c23bc3e07e4807ac17e358f812fd9c
        expression: abs(change(/Generic System properties by SNMP/system[firmware]))=1
        name: 'System: Firmware was changed on {HOST.NAME}'
        priority: INFO
        description: The firmware version on this host has been changed.
    - uuid: 59d7d4ade68e4895a3003ffdb2b99e9b
      name: 'System: device location'
      type: SNMP_AGENT
      snmp_oid: SNMPv2-MIB::sysLocation.0
      key: system[location]
      delay: '7200'
      history: 7d
      value_type: CHAR
      trends: '0'
      description: The physical location of this node (e.g., `telephone closet, 3rd
        floor').  If the location is unknown, the value is the zero-length string.
      inventory_link: LOCATION
      tags:
      - tag: Application
        value: System::Metrics
    - uuid: c78df2c804724633960efa97119b20ea
      name: 'System: device name'
      type: SNMP_AGENT
      snmp_oid: SNMPv2-MIB::sysName.0
      key: system[name]
      delay: '7200'
      history: 7d
      value_type: CHAR
      trends: '0'
      description: An administratively-assigned name for this managed node. By convention,
        this is the node's fully-qualified domain name.  If the name is unknown, the
        value is the zero-length string.
      inventory_link: NAME
      tags:
      - tag: Application
        value: System::Metrics
      triggers:
      - uuid: 564fcd8e77f449959547f50f54489524
        expression: abs(change(/Generic System properties by SNMP/system[name]))=1
        name: 'System: Hostname was changed on {HOST.NAME}'
        priority: INFO
        description: The configured hostname for this host has been changed.
    - uuid: ce079a92632e4bb48bca7f45215c150a
      name: 'System: serial number'
      type: SNMP_AGENT
      snmp_oid: '{$I_SYSTEM_SERIALNO_OID}'
      key: system[serial]
      delay: '14400'
      history: 14d
      value_type: TEXT
      trends: '0'
      inventory_link: SERIALNO_A
      tags:
      - tag: Application
        value: System::Metrics
    - uuid: a55c1a49767047ddac972cbca65857bf
      name: 'System: device type'
      type: SNMP_AGENT
      snmp_oid: '{$I_SYSTEM_TYPE_OID}'
      key: system[type]
      delay: '14400'
      history: 7d
      value_type: TEXT
      trends: '0'
      inventory_link: MODEL
      tags:
      - tag: Application
        value: System::Metrics
    macros:
    - macro: '{$I_SYSTEM_FIRMWARE_OID}'
      value: .1.3.6.1.2.1.47.1.1.1.1.10["index","1.3.6.1.2.1.47.1.1.1.1.5","3"]
    - macro: '{$I_SYSTEM_SERIALNO_OID}'
      value: 1.3.6.1.2.1.47.1.1.1.1.11["index","1.3.6.1.2.1.47.1.1.1.1.5","3"]
    - macro: '{$I_SYSTEM_TYPE_OID}'
      value: .1.3.6.1.2.1.47.1.1.1.1.13["index","1.3.6.1.2.1.47.1.1.1.1.5","3"]
    - macro: '{$T_SYSTEM_UPTIME_THRESH}'
      value: '3600'
    - macro: '{$V_SOFTWARE_APP_D}'
      value: .*
