zabbix_export:
  version: '7.0'
  template_groups:
  - uuid: 17dc7db2fd4542ca9d7c3f46e40baf97
    name: Retigra/Tasks/Network/Interfaces
  templates:
  - uuid: 45dc7400e2914f6d926439b479c66d95
    template: Ethernet Subinterfacs by SNMP
    name: Ethernet Subinterfacs by SNMP
    description: |
      This template is made for virtual ethernet interfaces, ie sub-interfaces and vlan-interfaces 

      iftype: https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib
    groups:
    - name: Retigra/Tasks/Network/Interfaces
    discovery_rules:
    - uuid: 7d9cd401d2354eaabaa10170db641c4a
      name: Virtual Sub-Interfaces
      type: SNMP_AGENT
      snmp_oid: discovery[{#SUBIFS},IF-MIB::ifName,{#IFTYPESUBIFS},IF-MIB::ifType]
      key: ifSubif
      delay: '3600'
      filter:
        evaltype: AND
        conditions:
        - macro: '{#IFTYPESUBIFS}'
          value: '{$L_REGEX_IFTYPE_SUBIFS}'
          formulaid: A
        - macro: '{#SUBIFS}'
          value: '{$L_REGEX_SUBIFS}'
          formulaid: B
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: |
        You may also consider using IF-MIB::ifType or IF-MIB::ifAlias for discovery depending on your filtering needs.

        Macro's are set as global macro.
      item_prototypes:
      - uuid: f60c523779214e35b2bae495df35b6a0
        name: Admin status of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAdminStatus.{#SNMPINDEX}
        key: ifAdminStatus[{#SUBIFS}]
        delay: '600'
        history: 7d
        trends: '0'
        description: The desired state of the interface.
        valuemap:
          name: SNMP interface status (ifAdminStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 91f142ea60bf49639abfeea344311b84
        name: Alias of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAlias.{#SNMPINDEX}
        key: ifAlias[{#SUBIFS}]
        delay: '3600'
        history: 7d
        value_type: CHAR
        trends: '0'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 2920a2869c27402bb7d545043a439fc5
        name: Description of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifDescr.{#SNMPINDEX}
        key: ifDescr[{#SUBIFS}]
        delay: '3600'
        history: 7d
        value_type: CHAR
        trends: '0'
        description: A textual string containing information about the interface.  This
          string should include the name of the manufacturer, the product name and
          the version of the interface hardware/software.
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: eabfd5d0af804010adf8ca8f051bd59b
        name: Incoming traffic on interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCInOctets.{#SNMPINDEX}
        key: ifHCInOctets[{#SUBIFS}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets in valid MAC frames received on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 16224050f7fc4c3385cf494450be5ebf
        name: Outgoing traffic on interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCOutOctets.{#SNMPINDEX}
        key: ifHCOutOctets[{#SUBIFS}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets transmitted in MAC frames on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: bb081498f88647bfb172fd398dd35485
        name: Operational status of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifOperStatus.{#SNMPINDEX}
        key: ifOperStatus[{#SUBIFS}]
        delay: '600'
        history: 7d
        trends: 30d
        description: The current operational state of the interface.
        valuemap:
          name: SNMP interface status (ifOperStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 8cc9d4b5454e40f78d02f63b3882f4a8
        name: Speed of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifSpeed.{#SNMPINDEX}
        key: ifSpeed[{#SUBIFS}]
        delay: '1800'
        history: 7d
        trends: 30d
        units: bps
        description: The current speed of the interface.
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: d47252577e334af7a1e7e5c90fcf3014
        name: Utilization threshold of interface $1 (bytes)
        type: CALCULATED
        key: UtilThreshBytes[{#SUBIFS}]
        delay: '600'
        history: 7d
        trends: 30d
        units: bps
        params: '{$T_INT_UTILIZATION}/100 *last(//ifSpeed[{#SUBIFS}])'
        description: Bandwidth utilization threshold set via macro
        tags:
        - tag: Application
          value: Network::Interfaces::Metadata
      - uuid: 086747f334bb49939f8056f13cec8f91
        name: Utilization threshold of interface $1 (%)
        type: CALCULATED
        key: UtilThreshPerc[{#SUBIFS}]
        delay: '600'
        history: 7d
        trends: 30d
        units: '%'
        params: '{$T_INT_UTILIZATION}'
        description: Bandwidth utilization threshold set via macro
        tags:
        - tag: Application
          value: Network::Interfaces::Metadata
      trigger_prototypes:
      - uuid: 4e681d4b89784f5cbbc9e1b2efb459ba
        expression: |
          last(/Ethernet Subinterfacs by SNMP/ifSpeed[{#SUBIFS}])>0 and 
          avg(/Ethernet Subinterfacs by SNMP/ifHCOutOctets[{#SUBIFS}],#3)> ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}/100 *last(/Ethernet Subinterfacs by SNMP/ifSpeed[{#SUBIFS}])) or length(last(/Ethernet Subinterfacs by SNMP/ifAlias[{#SUBIFS}]))<0
        name: Egress bandwidth utilization is over {$T_INT_UTILIZATION:"{#VIRTUALIFS}"}%
          on {HOST.NAME} interface {#VIRTUALIFS} {ITEM.VALUE3}
        status: DISABLED
        priority: WARNING
        description: Egress utilization is over the configured threshold value
      - uuid: 3e0bd6a5e95945a8876bfb026a7f3efc
        expression: |
          last(/Ethernet Subinterfacs by SNMP/ifSpeed[{#SUBIFS}])>0 and
          avg(/Ethernet Subinterfacs by SNMP/ifHCInOctets[{#SUBIFS}],#3)> ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}/100 *last(/Ethernet Subinterfacs by SNMP/ifSpeed[{#SUBIFS}])) or length(last(/Ethernet Subinterfacs by SNMP/ifAlias[{#SUBIFS}]))<0
        name: Ingress bandwidth utilization is over {$T_INT_UTILIZATION:"{#VIRTUALIFS}"}%
          on {HOST.NAME} interface {#VIRTUALIFS} {ITEM.VALUE3}
        status: DISABLED
        priority: WARNING
        description: Ingress utilization is over the configured threshold value
      - uuid: eec860f3fd1a4b99ae4aa17ca388be17
        expression: |
          last(/Ethernet Subinterfacs by SNMP/ifOperStatus[{#SUBIFS}])>1 and last(/Ethernet Subinterfacs by SNMP/ifAdminStatus[{#SUBIFS}])=1 
          and {$T_TRIGGER_PORT:"{#SNMPVALUE}"}=1 or length(last(/Ethernet Subinterfacs by SNMP/ifAlias[{#SUBIFS}]))<0
        name: Interface DOWN while administrative UP {HOST.NAME} {#VIRTUALIFS} {ITEM.VALUE3}
        priority: WARNING
        description: The operational status of this interface is down but the administrative
          status is up, some device(s) or a part of the network might be unreachable
      graph_prototypes:
      - uuid: 783a9cb42e6b448ea0ee4c0f51887304
        name: Traffic on interface {#VIRTUALIFS} - {?last(//ifAlias[{#VIRTUALIFS}])}
        graph_items:
        - drawtype: GRADIENT_LINE
          color: 00AA00
          item:
            host: Ethernet Subinterfacs by SNMP
            key: ifHCInOctets[{#SUBIFS}]
        - sortorder: '1'
          drawtype: GRADIENT_LINE
          color: 3333FF
          item:
            host: Ethernet Subinterfacs by SNMP
            key: ifHCOutOctets[{#SUBIFS}]
    macros:
    - macro: '{$L_REGEX_IFTYPE_SUBIFS}'
      value: '135'
    - macro: '{$L_REGEX_SUBIFS}'
      value: ^Eth|^Fa|^Gi|^Po
    - macro: '{$T_INT_UTILIZATION}'
      value: '60'
    - macro: '{$T_TRIGGER_PORT}'
      value: '1'
    valuemaps:
    - uuid: ad251fefbe7847c19a4eb4b4e2c0d2e8
      name: SNMP interface status (ifAdminStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
    - uuid: b6ac4c63520c4a779a9b656556036c00
      name: SNMP interface status (ifOperStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
      - value: '4'
        newvalue: unknown
      - value: '5'
        newvalue: dormant
      - value: '6'
        newvalue: notPresent
      - value: '7'
        newvalue: lowerLayerDown
