zabbix_export:
  version: '7.0'
  template_groups:
  - uuid: 17dc7db2fd4542ca9d7c3f46e40baf97
    name: Retigra/Tasks/Network/Interfaces
  templates:
  - uuid: 3c0030ad96494301bddf677592a31edd
    template: Ethernet Interfaces by SNMP
    name: Ethernet Interfaces by SNMP
    description: |
      Monitors ethernet based interfaces on a device via Low Level Discovery.
      Set the following macros as the discovery filters:

      * $L_REGEX_ETHERNET : Regexp to match interface names.
      * $L_REGEX_IFTYPE : Regexp to match iftype numbers in the IANA ifType MIB.

      See https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib for more info.
    groups:
    - name: Retigra/Tasks/Network/Interfaces
    discovery_rules:
    - uuid: 9dc3d0194fd64003996f52daf829fc85
      name: Ethernet interfaces
      type: SNMP_AGENT
      snmp_oid: discovery[{#SNMPVALUE},IF-MIB::ifName,{#IFTYPE},IF-MIB::ifType]
      key: ifName
      delay: '3600'
      filter:
        evaltype: AND
        conditions:
        - macro: '{#IFTYPE}'
          value: '{$L_REGEX_IFTYPE}'
          formulaid: A
        - macro: '{#SNMPVALUE}'
          value: '{$L_REGEX_ETHERNET}'
          formulaid: B
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: |
        You may also consider using IF-MIB::ifType or IF-MIB::ifAlias for discovery depending on your filtering needs.

        Macro's are set as global macro.
      item_prototypes:
      - uuid: f51234da7ae44e5d889be09ac8e2fb88
        name: 'Eth: Admin status of interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAdminStatus.{#SNMPINDEX}
        key: ifAdminStatus[{#SNMPVALUE}]
        delay: '600'
        history: 7d
        trends: '0'
        description: The desired state of the interface.
        valuemap:
          name: SNMP interface status (ifAdminStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 24dea4841a3443d080bbcd02ed9a3050
        name: 'Eth: Alias of interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAlias.{#SNMPINDEX}
        key: ifAlias[{#SNMPVALUE}]
        delay: '900'
        history: 7d
        value_type: CHAR
        trends: '0'
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: daac61c7a48644cf9a5051adb446c8cf
        name: 'Eth: Description of interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifDescr.{#SNMPINDEX}
        key: ifDescr[{#SNMPVALUE}]
        delay: '3600'
        history: 7d
        value_type: CHAR
        trends: '0'
        description: A textual string containing information about the interface.  This
          string should include the name of the manufacturer, the product name and
          the version of the interface hardware/software.
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 58af77b0006d4769843b41aed2ae961f
        name: 'Eth: Incoming traffic on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCInOctets.{#SNMPINDEX}
        key: ifHCInOctets[{#SNMPVALUE}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets in valid MAC frames received on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 44251689fb3046859d1d1460b29a3f28
        name: 'Eth: Outgoing traffic on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCOutOctets.{#SNMPINDEX}
        key: ifHCOutOctets[{#SNMPVALUE}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets transmitted in MAC frames on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: c3a56e640b52436faa7d448b4f115338
        name: 'Eth: Inbound discards on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifInDiscards.{#SNMPINDEX}
        key: ifInDiscards[{#SNMPVALUE}]
        delay: '1800'
        history: 7d
        trends: 30d
        description: The number of inbound packets which were chosen to be discarded
          even though no errors had been detected to prevent their being deliverable
          to a higher-layer protocol. One possible reason for discarding such a packet
          could be to free up buffer space.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: ed4d8563667e4d40aeeb450d5f07eeee
        name: 'Eth: Inbound errors on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifInErrors.{#SNMPINDEX}
        key: ifInErrors[{#SNMPVALUE}]
        delay: '1800'
        history: 7d
        trends: 30d
        description: For packet-oriented interfaces, the number of inbound packets
          that contained errors preventing them from being deliverable to a higher-layer
          protocol.  For character-oriented or fixed-length interfaces, the number
          of inbound transmission units that contained errors preventing them from
          being deliverable to a higher-layer protocol.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 627816cbc3d94c5189e9b6c470a56f7d
        name: 'Eth: Operational status of interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifOperStatus.{#SNMPINDEX}
        key: ifOperStatus[{#SNMPVALUE}]
        delay: '600'
        history: 7d
        trends: 30d
        description: The current operational state of the interface.
        valuemap:
          name: SNMP interface status (ifOperStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: a1ea407e60604b518b25782112d8a073
        name: 'Eth: Outbound discards on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifOutDiscards.{#SNMPINDEX}
        key: ifOutDiscards[{#SNMPVALUE}]
        delay: '1800'
        history: 7d
        trends: 30d
        description: The number of outbound packets which were chosen to be discarded
          even though no errors had been detected to prevent their being transmitted.
          One possible reason for discarding such a packet could be to free up buffer
          space.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 1490b04a185d447890dc71bff6a53c8c
        name: 'Eth: Outbound errors on interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifOutErrors.{#SNMPINDEX}
        key: ifOutErrors[{#SNMPVALUE}]
        delay: '1800'
        history: 7d
        trends: 30d
        description: For packet-oriented interfaces, the number of outbound packets
          that could not be transmitted because of errors. For character-oriented
          or fixed-length interfaces, the number of outbound transmission units that
          could not be transmitted because of errors.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: 55c57987c82c4a43bbc84554e8ede9d9
        name: 'Eth: Speed of interface $1'
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifSpeed.{#SNMPINDEX}
        key: ifSpeed[{#SNMPVALUE}]
        delay: '600'
        history: 7d
        trends: 30d
        units: bps
        description: The current speed of the interface.
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metrics
      - uuid: d856dbf00e474beba01fdd734109aa26
        name: 'Eth: Utilization threshold of interface $1 (bytes)'
        type: CALCULATED
        key: UtilThreshBytes[{#SNMPVALUE}]
        delay: '600'
        history: 7d
        trends: 30d
        units: bps
        params: '{$T_INT_UTILIZATION:"{#SNMPVALUE}"}/100 *last(//ifSpeed[{#SNMPVALUE}])'
        description: Bandwidth utilization threshold set via macro
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metadata
      - uuid: f8feea91c4504a90a6afb5ec4bff1c08
        name: 'Eth: Utilization threshold of interface $1 (%)'
        type: CALCULATED
        key: UtilThreshPerc[{#SNMPVALUE}]
        delay: '600'
        history: 7d
        trends: 30d
        units: '%'
        params: '{$T_INT_UTILIZATION:"{#SNMPVALUE}"}'
        description: Bandwidth utilization threshold set via macro
        tags:
        - tag: Application
          value: Network::Interfaces::Ethernet::Metadata
      trigger_prototypes:
      - uuid: d266c0a5740c4030b4686550a9c2525c
        expression: |
          last(/Ethernet Interfaces by SNMP/ifSpeed[{#SNMPVALUE}])>0 and 
          avg(/Ethernet Interfaces by SNMP/ifHCOutOctets[{#SNMPVALUE}],#3)> ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}/100 *last(/Ethernet Interfaces by SNMP/ifSpeed[{#SNMPVALUE}])) or length(last(/Ethernet Interfaces by SNMP/ifAlias[{#SNMPVALUE}]))<0
        name: Egress bandwidth utilization is over {$T_INT_UTILIZATION:"{#SNMPVALUE}"}%
          on {HOST.NAME} interface {#SNMPVALUE} {ITEM.VALUE4}
        priority: WARNING
        description: Egress bandwidth usage is {ITEM.VALUE2} which is over the configured
          utilization threshold ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}% of {ITEM.VALUE3})
          of interface {#SNMPVALUE}
      - uuid: 705fb3acd1f14be69ff199526ba1b815
        expression: |
          last(/Ethernet Interfaces by SNMP/ifSpeed[{#SNMPVALUE}])>0 and
          avg(/Ethernet Interfaces by SNMP/ifHCInOctets[{#SNMPVALUE}],#3)> ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}/100 *last(/Ethernet Interfaces by SNMP/ifSpeed[{#SNMPVALUE}])) or length(last(/Ethernet Interfaces by SNMP/ifAlias[{#SNMPVALUE}]))<0
        name: Ingress bandwidth utilization is over {$T_INT_UTILIZATION:"{#SNMPVALUE}"}%
          on {HOST.NAME} interface {#SNMPVALUE} {ITEM.VALUE4}
        priority: WARNING
        description: Ingress bandwidth usage is {ITEM.VALUE2} which is over the configured
          utilization threshold ({$T_INT_UTILIZATION:"{#SNMPVALUE}"}% of {ITEM.VALUE3})
          of interface {#SNMPVALUE}
      - uuid: 563873133aee4db7a32d00c570a24436
        expression: |
          last(/Ethernet Interfaces by SNMP/ifOperStatus[{#SNMPVALUE}])>1 and last(/Ethernet Interfaces by SNMP/ifAdminStatus[{#SNMPVALUE}])=1 
          and {$T_TRIGGER_PORT:"{#SNMPVALUE}"}=1 or length(last(/Ethernet Interfaces by SNMP/ifAlias[{#SNMPVALUE}]))<0
        name: Interface DOWN while administrative UP {HOST.NAME} {#SNMPVALUE} {ITEM.VALUE3}
        priority: WARNING
        description: The operational status of this interface is down but the administrative
          status is up, some device(s) or a part of the network might be unreachable
      graph_prototypes:
      - uuid: 5bde853ac97e4d85a7e476ca22106f11
        name: 'Eth: Traffic on interface {#SNMPVALUE} - {?last(//ifAlias[{#SNMPVALUE}])}'
        graph_items:
        - drawtype: GRADIENT_LINE
          color: 00AA00
          item:
            host: Ethernet Interfaces by SNMP
            key: ifHCInOctets[{#SNMPVALUE}]
        - sortorder: '1'
          drawtype: GRADIENT_LINE
          color: 3333FF
          item:
            host: Ethernet Interfaces by SNMP
            key: ifHCOutOctets[{#SNMPVALUE}]
    macros:
    - macro: '{$L_REGEX_ETHERNET}'
      value: ^Ethernet|^FastEthernet|^GigabitEthernet|^Eth[0-9]|^Fa[0-9]|^Gi[0-9]|^Po
    - macro: '{$L_REGEX_IFTYPE}'
      value: 6|53
    - macro: '{$T_INT_UTILIZATION}'
      value: '60'
    - macro: '{$T_TRIGGER_PORT}'
      value: '1'
    valuemaps:
    - uuid: 04e1d87a06b0414aaa7051d0c69bfe28
      name: SNMP interface status (ifAdminStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
    - uuid: 81e02af001674b6fa7ea0829addca55d
      name: SNMP interface status (ifOperStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
      - value: '4'
        newvalue: unknown
      - value: '5'
        newvalue: dormant
      - value: '6'
        newvalue: notPresent
      - value: '7'
        newvalue: lowerLayerDown
