zabbix_export:
  version: '7.0'
  template_groups:
  - uuid: 17dc7db2fd4542ca9d7c3f46e40baf97
    name: Retigra/Tasks/Network/Interfaces
  templates:
  - uuid: 68c9c2b1ca5c49c78f033ab49e0e7032
    template: VTI Network Interfaces by SNMP
    name: VTI Network Interfaces by SNMP
    description: |
      This template is made for virtual tunnel interfaces

      iftype: https://www.iana.org/assignments/ianaiftype-mib/ianaiftype-mib
    groups:
    - name: Retigra/Tasks/Network/Interfaces
    discovery_rules:
    - uuid: 8c34314088ff49e7b347b1ab62007ad9
      name: Virtual Tunnel Interfaces
      type: SNMP_AGENT
      snmp_oid: discovery[{#TUNNELIFS},IF-MIB::ifName,{#IFTYPE},IF-MIB::ifType]
      key: ifTunnel
      delay: '900'
      filter:
        evaltype: AND
        conditions:
        - macro: '{#IFTYPE}'
          value: '{$L_REGEX_IFTYPE_VTI}'
          formulaid: A
        - macro: '{#TUNNELIFS}'
          value: '{$L_REGEX_VTI}'
          formulaid: B
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: |
        You may also consider using IF-MIB::ifType or IF-MIB::ifAlias for discovery depending on your filtering needs.

        Macro's are set as global macro.
      item_prototypes:
      - uuid: b6dc8125777f4cbfb65110de9829ee7c
        name: Admin status of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAdminStatus.{#SNMPINDEX}
        key: ifAdminStatus[{#TUNNELIFS}]
        delay: '600'
        history: 7d
        trends: '0'
        description: The desired state of the interface.
        valuemap:
          name: SNMP interface status (ifAdminStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 2952e3ebf80d47a9a85ff2ede6951138
        name: Alias of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifAlias.{#SNMPINDEX}
        key: ifAlias[{#TUNNELIFS}]
        delay: '900'
        history: 7d
        value_type: CHAR
        trends: '0'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 0996ca37318345ce9814b6ff1eda27bc
        name: Description of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifDescr.{#SNMPINDEX}
        key: ifDescr[{#TUNNELIFS}]
        delay: '3600'
        history: 7d
        value_type: CHAR
        trends: '0'
        description: A textual string containing information about the interface.  This
          string should include the name of the manufacturer, the product name and
          the version of the interface hardware/software.
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 65d6cd1aca1e4779899d9d5aabea0c10
        name: Incoming traffic on interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCInOctets.{#SNMPINDEX}
        key: ifHCInOctets[{#TUNNELIFS}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets in valid MAC frames received on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 2b73f753e33341f68cdd7307880b251e
        name: Outgoing traffic on interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifHCOutOctets.{#SNMPINDEX}
        key: ifHCOutOctets[{#TUNNELIFS}]
        delay: '300'
        history: 7d
        units: bps
        description: The number of octets transmitted in MAC frames on this interface,
          including the MAC header and FCS.
        preprocessing:
        - type: CHANGE_PER_SECOND
          parameters:
          - ''
        - type: MULTIPLIER
          parameters:
          - '8'
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      - uuid: 2eaa58a14f7f4f6c888bca312011f622
        name: Operational status of interface $1
        type: SNMP_AGENT
        snmp_oid: IF-MIB::ifOperStatus.{#SNMPINDEX}
        key: ifOperStatus[{#TUNNELIFS}]
        delay: '600'
        history: 7d
        trends: 30d
        description: The current operational state of the interface.
        valuemap:
          name: SNMP interface status (ifOperStatus)
        tags:
        - tag: Application
          value: Network::Interfaces::Metrics
      trigger_prototypes:
      - uuid: a395f032f4064ebaa4a364bc14e4cf9e
        expression: (last(/VTI Network Interfaces by SNMP/ifOperStatus[{#TUNNELIFS}])>1
          and last(/VTI Network Interfaces by SNMP/ifAdminStatus[{#TUNNELIFS}])=1
          and {$T_TRIGGER_PORT:"{#TUNNELIFS}"}=1 and {$T_ACTIVE_NODE:"{#TUNNELIFS}"}=1)
          or length(last(/VTI Network Interfaces by SNMP/ifAlias[{#TUNNELIFS}]))<0
        name: Interface DOWN while administrative UP {HOST.NAME} {#TUNNELIFS} {ITEM.VALUE3}
        priority: WARNING
        description: The operational status of this interface is down but the administrative
          status is up, some device(s) or a part of the network might be unreachable
      graph_prototypes:
      - uuid: 856f223873e7424797b1315d109a57ad
        name: Traffic on interface {#TUNNELIFS} - {?last(//ifAlias[{#TUNNELIFS}])}
        graph_items:
        - drawtype: GRADIENT_LINE
          color: 00AA00
          item:
            host: VTI Network Interfaces by SNMP
            key: ifHCInOctets[{#TUNNELIFS}]
        - sortorder: '1'
          drawtype: GRADIENT_LINE
          color: 3333FF
          item:
            host: VTI Network Interfaces by SNMP
            key: ifHCOutOctets[{#TUNNELIFS}]
    macros:
    - macro: '{$L_REGEX_IFTYPE_VTI}'
      value: '131'
    - macro: '{$L_REGEX_VTI}'
      value: ^Tu
    - macro: '{$T_TRIGGER_PORT}'
      value: '0'
    valuemaps:
    - uuid: 1f15b41b7aef41c5a79ea73d1c6f043d
      name: SNMP interface status (ifAdminStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
    - uuid: 2f7d36da6ac84c748837bd13a89ede85
      name: SNMP interface status (ifOperStatus)
      mappings:
      - value: '1'
        newvalue: up
      - value: '2'
        newvalue: down
      - value: '3'
        newvalue: testing
      - value: '4'
        newvalue: unknown
      - value: '5'
        newvalue: dormant
      - value: '6'
        newvalue: notPresent
      - value: '7'
        newvalue: lowerLayerDown
