zabbix_export:
  version: '7.0'
  template_groups:
  - uuid: ce925f2eb4b14bc2a13543a194e79013
    name: Retigra/Tasks/System/Cisco
  templates:
  - uuid: 3e476967470d4596b8738f1be7a4cd33
    template: Cisco Environment by SNMP
    name: Cisco Environment by SNMP
    groups:
    - name: Retigra/Tasks/System/Cisco
    discovery_rules:
    - uuid: ef88c16348fd473bab42a7fd5afc48d8
      name: Device fans
      type: SNMP_AGENT
      snmp_oid: discovery[{#FANNAME},.1.3.6.1.4.1.9.9.13.1.4.1.2]
      key: DevFans
      delay: '1800'
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: Discovery of Cisco Fans
      item_prototypes:
      - uuid: 526d9309821c43f1886963c6297432b0
        name: Status of $1
        type: SNMP_AGENT
        snmp_oid: .1.3.6.1.4.1.9.9.13.1.4.1.3.{#SNMPINDEX}
        key: FanState[{#FANNAME}]
        delay: '600'
        history: 90d
        valuemap:
          name: Cisco EnvMon State
        tags:
        - tag: Application
          value: System::Metrics
        trigger_prototypes:
        - uuid: 512cf6f4ac16416abec96b2324c6ac70
          expression: last(/Cisco Environment by SNMP/FanState[{#FANNAME}])<>1 and
            last(/Cisco Environment by SNMP/FanState[{#FANNAME}])<>5
          name: 'FAN sensor {HOST.NAME} #FANNAME has status {ITEM.VALUE1}'
          priority: WARNING
    - uuid: 2045edee1f914f79b09f1472022c5e9d
      name: Device Powersupplies
      type: SNMP_AGENT
      snmp_oid: discovery[{#PSUNAME},.1.3.6.1.4.1.9.9.13.1.5.1.2]
      key: DevPowersupplies
      delay: '1800'
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: Discovery of Cisco Powersupplies
      item_prototypes:
      - uuid: cbdfd253b4bf4d1ea7d2729a98bb382f
        name: Status of PowerSupply $1
        type: SNMP_AGENT
        snmp_oid: .1.3.6.1.4.1.9.9.13.1.5.1.3.{#SNMPINDEX}
        key: PSUState[{#PSUNAME}]
        delay: '600'
        history: 90d
        valuemap:
          name: Cisco EnvMon State
        tags:
        - tag: Application
          value: System::Metrics
        trigger_prototypes:
        - uuid: 58f62c5fd1b049d193611493f946881b
          expression: last(/Cisco Environment by SNMP/PSUState[{#PSUNAME}])<>1 and
            last(/Cisco Environment by SNMP/PSUState[{#PSUNAME}])<>5
          name: PSU sensor {HOST.NAME} {#PSUNAME} has status {ITEM.VALUE1}
          priority: WARNING
    - uuid: 9d2c0ef8e3d3482bbf8fc3c7ba23706f
      name: Device temp sensors
      type: SNMP_AGENT
      snmp_oid: discovery[{#TEMPSENSORNAME},.1.3.6.1.4.1.9.9.13.1.3.1.2]
      key: DevTempSensors
      delay: '1800'
      lifetime: 14d
      enabled_lifetime_type: DISABLE_NEVER
      description: Discovery of Cisco temperature sensors
      item_prototypes:
      - uuid: 5264e71a631242ee8f6b5d1e23dc69c1
        name: Status of temperature sensor $1
        type: SNMP_AGENT
        snmp_oid: .1.3.6.1.4.1.9.9.13.1.3.1.6.{#SNMPINDEX}
        key: TempState[{#TEMPSENSORNAME}]
        delay: '600'
        history: 90d
        valuemap:
          name: Cisco EnvMon State
        tags:
        - tag: Application
          value: System::Metrics
        trigger_prototypes:
        - uuid: cb1defe7145747318dd25364743f2d30
          expression: last(/Cisco Environment by SNMP/TempState[{#TEMPSENSORNAME}])<>1
            and last(/Cisco Environment by SNMP/TempState[{#TEMPSENSORNAME}])<>5
          name: Temperature sensor {HOST.NAME} {#TEMPSENSORNAME} has status {ITEM.VALUE1}
          priority: WARNING
    valuemaps:
    - uuid: f7f559bc1dc94a5291b7d12e02db83b9
      name: Cisco EnvMon State
      mappings:
      - value: '1'
        newvalue: normal
      - value: '2'
        newvalue: warning
      - value: '3'
        newvalue: critical
      - value: '4'
        newvalue: shutdown
      - value: '5'
        newvalue: notPresent
      - value: '6'
        newvalue: notFunctioning
